export default {

  // App actions
  APP_INITIALIZE: 'APP_INITIALIZE',

  STORE_UPDATED: 'STORE_UPDATED',

  LIST_HIDE_LOADING_STATUS: 'LIST_HIDE_LOADING_STATUS',

  ITEM_MARK_COMPLETE: 'ITEM_MARK_COMPLETE',
  ITEM_DELETE: 'ITEM_DELETE',
  ITEM_USER_IS_EDITING: 'ITEM_USER_IS_EDITING',

  SERVER_JOIN_ROOM: 'SERVER_JOIN_ROOM',
  SERVER_LIST_LOADED: 'SERVER_LIST_LOADED',
  SERVER_LIST_NOT_FOUND: 'SERVER_LIST_NOT_FOUND',
  SERVER_LIST_INITIAL_LOAD: 'SERVER_LIST_INITIAL_LOAD',
  SERVER_LIST_USER_UPDATED: 'SERVER_LIST_USER_UPDATED',
  SERVER_LIST_PEER_UPDATED: 'SERVER_LIST_PEER_UPDATED',
  SERVER_ITEM_PEER_IS_EDITING: 'SERVER_ITEM_PEER_IS_EDITING',

};
